const _serviceProvider = document.getElementById("serviceProvider")
const _username = document.getElementById("username")
const _password = document.getElementById("password")
const _from = document.getElementById("from")
const _to = document.getElementById("to")
const _cc = document.getElementById("cc")
const _bcc = document.getElementById("bcc")
const _text = document.getElementById("text")
const _html = document.getElementById("html")
const _file = document.getElementById("file")

